basePath: /
definitions:
  controller.DosenWali:
    properties:
      alamat:
        example: Jalan Pengangsaan Timur
        type: string
      email:
        example: megachan@gmail.cxt
        type: string
      nama_dosen:
        description: ID           primitive.ObjectID `bson:"_id,omitempty" json:"_id,omitempty"
          example:"7686535656"`
        example: Megawati
        type: string
      phone_number:
        example: "64545678734"
        type: string
    type: object
  controller.JamKerja:
    properties:
      durasi:
        example: 8
        type: integer
      gmt:
        example: 7
        type: integer
      hari:
        example:
        - Senin
        - Selasa
        - Rabu
        - Kamis
        - Jumat
        - Sabtu
        - Minggu
        items:
          type: string
        type: array
      jam_keluar:
        example: "16:00"
        type: string
      jam_masuk:
        example: "08:00"
        type: string
      piket_tim:
        example: Piket Z
        type: string
      shift:
        example: 2
        type: integer
    type: object
  controller.Karyawan:
    properties:
      hari_kerja:
        example:
        - Senin
        - Selasa
        - Rabu
        - Kamis
        - Jumat
        - Sabtu
        - Minggu
        items:
          type: string
        type: array
      jabatan:
        example: Anonymous
        type: string
      jam_kerja:
        items:
          $ref: '#/definitions/controller.JamKerja'
        type: array
      nama:
        description: ID          primitive.ObjectID `bson:"_id,omitempty" json:"_id,omitempty"
          example:"123456789"`
        example: Tes Swagger
        type: string
      phone_number:
        example: "08123456789"
        type: string
    type: object
  controller.Mahasiswa:
    properties:
      jekel:
        example: Laki-Laki
        type: string
      nama:
        description: ID           primitive.ObjectID `bson:"_id,omitempty" json:"_id,omitempty"
          example:"123456789"`
        example: Ade Candra
        type: string
      npm:
        example: 1214048
        type: integer
      phone_number:
        example: "0897653421"
        type: string
    type: object
  controller.Monitoring:
    properties:
      dosen:
        $ref: '#/definitions/controller.DosenWali'
      hari:
        example: jumat
        type: string
      ortu:
        allOf:
        - $ref: '#/definitions/controller.OrangTua'
        description: ID       primitive.ObjectID `bson:"_id,omitempty" json:"_id,omitempty"
          example:"565455478"`
      tanggal:
        example: 17-08-1945
        type: string
      tema:
        $ref: '#/definitions/controller.Tema'
    type: object
  controller.OrangTua:
    properties:
      anak:
        $ref: '#/definitions/controller.Mahasiswa'
      nama_ot:
        description: ID           primitive.ObjectID `bson:"_id,omitempty" json:"_id,omitempty"
          example:"125436798"`
        example: Boy William
        type: string
      phone_number:
        example: "8769765590"
        type: string
    type: object
  controller.Presensi:
    properties:
      biodata:
        $ref: '#/definitions/controller.Karyawan'
      checkin:
        description: Datetime     primitive.DateTime `bson:"datetime,omitempty" json:"datetime,omitempty"`
        example: MASUK
        type: string
      latitude:
        example: 123.11
        type: number
      location:
        example: Bandung
        type: string
      longitude:
        description: ID           primitive.ObjectID `bson:"_id,omitempty" json:"_id,omitempty"
          example:"123456789"`
        example: 123.11
        type: number
      phone_number:
        example: "08123456789"
        type: string
    type: object
  controller.Tema:
    properties:
      nama_tema:
        description: ID        primitive.ObjectID `bson:"_id,omitempty" json:"_id,omitempty"
          example:"5474574574"`
        example: penjajahan
        type: string
    type: object
host: farel-app.herokuapp.com
info:
  contact:
    email: fareldazz123@gmail.com
    name: API Support
    url: https://github.com/FarelND29
  description: This is a sample server
  title: Swagger Example API
  version: "1.0"
paths:
  /all-monitoring:
    get:
      consumes:
      - application/json
      description: Mengambil semua data presensi.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Monitoring'
      summary: Get All Data Monitoring.
      tags:
      - Monitoring
  /del/monitoring/{id}:
    delete:
      consumes:
      - application/json
      description: Hapus data monitoring.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Delete data monitoring.
      tags:
      - Monitoring
  /delete/{id}:
    delete:
      consumes:
      - application/json
      description: Hapus data presensi.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Delete data presensi.
      tags:
      - Presensi
  /ins:
    post:
      consumes:
      - application/json
      description: Input data presensi.
      parameters:
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.Presensi'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Presensi'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Insert data presensi.
      tags:
      - Presensi
  /ins/monitoring:
    post:
      consumes:
      - application/json
      description: Input data monitoring.
      parameters:
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.Monitoring'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Monitoring'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Insert data monitoring.
      tags:
      - Monitoring
  /monitoring/{id}:
    get:
      consumes:
      - application/json
      description: Ambil per ID data monitoring.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Monitoring'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get By ID Data Monitoring.
      tags:
      - Monitoring
  /presensi:
    get:
      consumes:
      - application/json
      description: Mengambil semua data presensi.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Presensi'
      summary: Get All Data Presensi.
      tags:
      - Presensi
  /presensi/{id}:
    get:
      consumes:
      - application/json
      description: Ambil per ID data presensi.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Presensi'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get By ID Data Presensi.
      tags:
      - Presensi
  /upd/{id}:
    put:
      consumes:
      - application/json
      description: Ubah data presensi.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.Presensi'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Presensi'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Update data presensi.
      tags:
      - Presensi
  /upd/monitoring/{id}:
    put:
      consumes:
      - application/json
      description: Ubah data monitoring.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.Monitoring'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Monitoring'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Update data monitoring.
      tags:
      - Monitoring
schemes:
- http
- https
swagger: "2.0"
